// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWbxDPx2k6hU_Sbz2lN_higoQkgS7SkOQ',
    appId: '1:463899795145:android:c5d12f7bae8cce8c2eb718',
    messagingSenderId: '463899795145',
    projectId: 'questly-efe89',
    storageBucket: 'questly-efe89.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkIVCuW5AhSv2GvRY5Z_Cj6eeKulvLqD0',
    appId: '1:463899795145:ios:079999880dc8e47c2eb718',
    messagingSenderId: '463899795145',
    projectId: 'questly-efe89',
    storageBucket: 'questly-efe89.firebasestorage.app',
    iosBundleId: 'com.questly.questly',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJa-cashmuwaa5yv9wfqIFLfZt7BOrY4g',
    appId: '1:463899795145:web:192c59f18426d2352eb718',
    messagingSenderId: '463899795145',
    projectId: 'questly-efe89',
    authDomain: 'questly-efe89.firebaseapp.com',
    storageBucket: 'questly-efe89.firebasestorage.app',
  );
}
